import Testimonials from "@/components/AboutUs/Testimonials";
import AllCourses from "@/components/AllCourses/AllCourses";

export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};

const Course = () => {
  return (
    <div>
      <section className="py-5">
        <div className="container">
          <div className="row pt-5 text-center">
            <div className="col-md-2" />
            <div className="col-md-8 mt-4 mb-4">
              <h1 className="blog-h1">কোর্স সমূহ</h1>
              <p className="couser-text">
                বর্তমান বিশ্বের ট্রেন্ডি এবং চাহিদাসম্পন্ন সব কোর্স রয়েছে
                ক্রিয়েটিভ আইটি ইন্সটিটিউটে। কোর্স করার সময় যে প্রয়োজনীয়
                কনফিগারেশনের কম্পিউটার দরকার, তার সবই রয়েছে আমাদের ল্যাবে। আপনি
                চাইলেই ক্লাস শেষে ল্যাবে বসে কোর্স বিষয়ক যেকোনো কিছু প্র্যাকটিস
                করতে পারেন। প্রতিটি কোর্স এমনভাবে সাজানো হয়েছে, যাতে কোর্স শেষে
                প্রতিটি টপিকে কাজ করার আত্মবিশ্বাস আপনার থাকে
              </p>
            </div>
            <div className="col-md-2" />
          </div>
        </div>
      </section>

      <AllCourses/>

      <Testimonials/>
    </div>
  );
};

export default Course;
