import { Inter } from "next/font/google";

import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

import "bootstrap/dist/css/bootstrap.css";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Top-it-institute",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#ED1C24" height={2} speed={200} showSpinner={false}/>
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
